# This RayJob is based on the "Finetuning a Pytorch Image Classifier with Ray Train" example in the Ray documentation.
# See https://docs.ray.io/en/latest/train/examples/pytorch/pytorch_resnet_finetune.html for more details.
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: pytorch-image-classifier
spec:
  shutdownAfterJobFinishes: true
  entrypoint: python ray-operator/config/samples/pytorch-resnet-image-classifier/fine-tune-pytorch-resnet-image-classifier.py
  runtimeEnvYAML: |
    pip:
      - numpy
      - datasets
      - torch
      - torchvision
      - transformers>=4.19.1
    working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.9.0
              env:
              - name: NUM_WORKERS
                value: "4"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "1"
                  memory: "8G"
                requests:
                  cpu: "1"
                  memory: "8G"
              volumeMounts:
                - mountPath: /tmp/ray
                  name: ray-logs
                - mountPath: /mnt/cluster_storage
                  name: cluster-storage
          volumes:
            - name: ray-logs
              emptyDir: {}
            - name: cluster-storage
              emptyDir: {}
    workerGroupSpecs:
      - replicas: 4
        minReplicas: 4
        maxReplicas: 4
        groupName: gpu-group
        rayStartParams:
          dashboard-host: '0.0.0.0'
        template:
          spec:
            serviceAccountName: pytorch-distributed-training
            containers:
              - name: ray-worker
                image: rayproject/ray-ml:2.9.0-gpu
                resources:
                  limits:
                    cpu: "1"
                    memory: "8G"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "1"
                    memory: "8G"
                    nvidia.com/gpu: "1"
                volumeMounts:
                  - mountPath: /tmp/ray
                    name: ray-logs
                  - mountPath: /mnt/cluster_storage
                    name: cluster-storage
            volumes:
              - name: ray-logs
                emptyDir: {}
              - name: cluster_storage
                emptyDir: {}