apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: al2-neuron
  annotations:
    kubernetes.io/description: "EC2NodeClass for running Neuron nodes"
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-karpenter-blueprints" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "karpenter-blueprints" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "karpenter-blueprints" # replace with your cluster name
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 128Gi
        deleteOnTermination: true