
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: neuron
  annotations:
    kubernetes.io/description: "General purpose NodePool for Neuron generic workloads"
spec:
  template:
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["inf2", "trn1", "trn1n"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: "NoSchedule"
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: al2-neuron
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 24h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: al2-neuron
  annotations:
    kubernetes.io/description: "EC2NodeClass for running Neuron nodes"
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-karpenter-blueprints" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "karpenter-blueprints" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "karpenter-blueprints" # replace with your cluster name
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 128Gi
        deleteOnTermination: true