apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: default
type: Opaque
data:
  # You need to encode token into base64. 
  # echo <YOURTOKEN> | base64
  token: "REPLACE_WITH_TOKEN"