apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-vllm-neuron
spec:
  predictor:
    model:
      modelFormat:
        name: vllm
      runtime: kserve-vllm-neuron
