apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-kserve
  namespace: kserve-test
spec:
  predictor:
    containerConcurrency: 1
    nodeSelector:
      karpenter.sh/nodepool: gpu
      karpenter.k8s.aws/instance-family: g5
      # node.kubernetes.io/instance-type: g6.xlarge
    containers:
    - command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - --port
        - "8080"
        - --model
        - TinyLlama/TinyLlama-1.1B-Chat-v1.0
      image:  kserve/vllmserver:latest
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
      name: kserve-container
      volumeMounts:
      - name: shmem
        mountPath: /dev/shm
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 8Gi
          nvidia.com/gpu: "1"
    volumes:
    - name: shmem
      emptyDir:
          medium: Memory